apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      restartPolicy: Never
      containers:
      - name: hello-world
        image: hello-world
        ports:
        - containerPort: 80
