version: '3'
services:
  go:
    build: ./go-app
    container_name: go-app

  java:
    build: ./java-app
    container_name: java-app

  nginx-lb:
    build: ./nginx 
    container_name: nginx
    ports:
      - "8080:8080"
    depends_on:
      - go
      - java

